---
- name: Deploy and start Apache HTTPD service
  hosts: webserver
  vars:
    web_pkg: nginx 
    firewall_pkg: firewalld
    web_service: nginx
    firewall_service: firewalld
    python_pkg: python3-PyMySQL
    rule: http

  tasks:
    - name: Required packages are installed and up to date
      yum:
        name:
          - "{{ web_pkg  }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest

#### New Debug output to show variables
#

    - name: The variables are
      debug:
        msg: The value of web_pkg is "{{ web_pkg }}"

    - name: The variables are {{ web_service }} for web_service variable
      debug:
        msg: The value of web_service is "{{ web_service }}" or without quotes as \{\{ web_service \}} for the variable web_service.       
        
#### End Debug output 
#

    - name: The {{ firewall_service }} service is started and enabled
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: The {{ web_service }} service is started and enabled
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started

    - name: Web content is in place
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: The firewall port for {{ rule }} is open
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

- name: Verify the Apache service
  hosts: localhost
  become: false
  tasks:
    - name: Ensure the webserver is reachable
      uri:
        url: http://servera.lab.example.com
        status_code: 200
