---
- name: Install and configure webserver with basic auth
  hosts: webserver
  vars:
    firewall_pkg: firewalld
    firewall_svc: firewalld
    web_pkg:  httpd
    web_svc:  httpd
    ssl_pkg:  mod_ssl
    httpdconf_src: files/httpd.conf
    httpdconf_dest: /etc/httpd/conf/httpd.conf
    htaccess_src: files/.htaccess
    secrets_dir:  /etc/httpd/secrets
    secrets_src:  files/htpasswd
    secrets_dest: "{{ secrets_dir }}/htpasswd"
    web_root: /var/www/html
  tasks:
      - name: lastest version of the necessary packages installed
        ansible.builtin.dnf:
          name:
            - "{{ firewall_pkg }}"
            - "{{ web_pkg }}"
            - "{{ ssl_pkg }}"
          state: latest
  
      - name: configure web service
        ansible.builtin.copy:
          src:  "{{ httpdconf_src }}"
          dest: "{{ httpdconf_dest }}"
          owner: root
          group: root
          mode: 0644

      - name: secrets directory exist
        ansible.builtin.file:
          path: "{{ secrets_dir }}"
          state:  directory
          owner: apache
          group:  apache
          mode: 0500

      - name: htpasswd file exist
        ansible.builtin.copy:
          src: "{{ secrets_src }}"
          dest: "{{ secrets_dest }}"
          owner: apache
          group: apache
          mode: 0400

      - name: .htaccess file installed in docroot
        ansible.builtin.copy:
          src: "{{ htaccess_src }}"
          dest: "{{ web_root }}/.htaccess"
          owner: apache
          group: apache
          mode: 0400

      - name: create index.html
        ansible.builtin.copy:
          content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts['default_ipv4']['address'] }}) has been customized by Ansible.\n"
          dest: "{{ web_root }}/index.html"

      - name: firewall service enabled and started
        ansible.builtin.service:
          name: "{{ firewall_svc }}"
          state: started
          enabled:  true

      - name: Open the port for the web server
        ansible.posix.firewalld:
          service: https
          state: enabled
          immediate: true
          permanent: true

      - name: web service enabled and started
        ansible.builtin.service:
          name: "{{ web_svc }}"
          state:  started
          enabled: true
- name: test web server with basic auth
  hosts: workstation
  become: false
  vars:
    web_user: guest
  vars_files:
      - vars/secret.yml
  tasks:
      - name: connect to web server with basic auth
        ansible.builtin.uri:
          url: https://serverb.lab.example.com
          validate_certs: no
          force_basic_auth: yes
          user: "{{ web_user }}"
          password: "{{ web_pass }}"
          return_content: yes
          status_code:  200
        register: auth_test

      - ansible.builtin.debug:
          var: auth_test.content

