---
- name: Demo playbook for handlers and failed tasks
  hosts: servera
  force_handlers: no
  
  tasks:
    - name: a task which always notifies its handler because it evaluates as true
      ansible.builtin.command: /bin/true
      notify: Handler was notified
      ignore_errors: true

    - name: Task that failed
      ansible.builtin.command: /bin/false
      ignore_errors: false

    - name: Third task runs when ignore errors true
      ansible.builtin.debug: 
        msg: I'm the 3rd task

  handlers:
    - name: Handler was notified
      ansible.builtin.debug:
        msg: This handler was notified even though there were issues with the task called after notifying the handler.
