
---
- name: Installs a package and prints the result
  hosts: servera
  tasks:
    - name: Install the package
      yum:
        name: httpd
        state: installed
      register: install_result

    - name: A {{ install_result.results  }} was installed!!!
      debug: var=install_result.results
