
---
- name: Install and start Apache HTTPD
  hosts: web
  tasks:
    - name: httpd package is present
      yum:
        name:
          - httpd
          - firewalld
        state: present

    - name: Create an Index.HTML File
      copy:
        content: This is a test page on Apache!!
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true

    - name: Firewall is Enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: HTTP Service is Open on Firewall
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: yes
