---
  - name: Install the firewall
    yum:
      name: "{{ firewall_pkg }}"
      state: latest

  - name: Start the firewall
    service:
      name: "{{ firewall_svc }}"
      enabled: true
      state: started

  - name: Open the port for {{ rule }}
    firewalld:
      service: "{{ item }}"
      immediate: true
      permanent: true
      state: enabled
    loop: "{{ rule }}"
